// vuejs/src/components/checkbox.vue
<template>
  <div class="container">
    <div>
      <h2>Combien voulez-vous de citations ?</h2>
    </div>
    <div id="inlineRadio">
      <label class="checkbox-inline">
        <input type="radio" name="inlineRadioOptions" value="1" checked />1
      </label>
      <label class="checkbox-inline">
        <input type="radio" name="inlineRadioOptions" value="2" required />2
      </label>
      <label class="checkbox-inline">
        <input type="radio" name="inlineRadioOptions" value="3" required />3
      </label>
      <label class="checkbox-inline">
        <input type="radio" name="inlineRadioOptions" value="4" required />4
      </label>
      <label class="checkbox-inline">
        <input type="radio" name="inlineRadioOptions" value="5" required />5
      </label>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Checkbox',
};
</script>

<style scoped>
.container {
  display: block;
  width: 50%;
  height: auto;
}

h5 {
  font-size: 1.8em;
  font-weight: bold;
}

@media screen and (max-width: 800px) {
  .container {
    width: 100%;
  }
}
</style>

// react-v/src/components/Checkbox.js
import React from 'react'
import './Checkbox.css'

const CheckBox = () => (
    <div className="container">
        <div id="inlineRadio">
        <h2>Nombre de citations</h2>
        <label className="radio-inline">
            <input type="radio" name="inlineRadioOptions" value="1" defaultChecked />1
        </label>
        <label className="radio-inline">
            <input type="radio" name="inlineRadioOptions" value="2" required />2
        </label>
        <label className="radio-inline">
            <input type="radio" name="inlineRadioOptions" value="3" required />3
        </label>
        <label className="radio-inline">
            <input type="radio" name="inlineRadioOptions" value="4" required />4
        </label>
        <label className="radio-inline">
            <input type="radio" name="inlineRadioOptions" value="5" required />5
        </label>
    </div>
  </div>
)

export default CheckBox
